### PR TITLE
Adding Python 3.6

### PR DESCRIPTION
**Pull request by IlianIliev**

### CODE REVIEW

**Comment by IlianIliev** [comment]
@derekkwok Hey, just wanted to check if this project is still active or should I close the PR?

**Comment by SentinelWarren** [comment]
hi @IlianIliev seems like @derekkwok is not available anymore, maybe we should keep working on this on a different fork?

**Comment by IlianIliev** [comment]
@SentinelWarren actually I am not sure if anyone is still using the project. I wouldn't mind working on it though.

**Comment by SentinelWarren** [comment]
@IlianIliev  Yah, you do have a point! so what do you suggest so far??

**Comment by IlianIliev** [comment]
How about making a small research whether there are other alternatives for OS X if you want to install multiple Python versions and talk again

**Comment by EmilStenstrom** [comment]
I was previously using this library, but I think the modern way to install different versions is to use pyenv. I'll try using this guide and see if I can get it working: https://weknowinc.com/blog/running-multiple-python-versions-mac-osx

Update: It works great. I'm no longer using this recipe to install different python versions.

**Comment by IlianIliev** [comment]
Closing this one as I don't think it is relevant nowadays.

**Pull request closed without merging**
